
CREATE USER BFAC IDENTIFIED BY BFAC;

GRANT CONNECT TO BFAC;
GRANT RESOURCE TO BFAC;

ALTER USER BFAC DEFAULT TABLESPACE DAT_B01;
ALTER USER BFAC TEMPORARY TABLESPACE TEMP;

CREATE USER BFAC_APP IDENTIFIED BY BFAC_APP;

GRANT CONNECT TO BFAC_APP;
GRANT RESOURCE TO BFAC_APP;

ALTER USER BFAC_APP DEFAULT TABLESPACE DAT_B01;
ALTER USER BFAC_APP TEMPORARY TABLESPACE TEMP;

DROP TABLE BFAC.STAMP_REQUEST;

CREATE TABLE BFAC.STAMP_REQUEST (
OBJECT_HASH VARCHAR2(100) NOT NULL, 
CREATE_TS DATE DEFAULT SYSDATE NOT NULL ,
FORCE_SINGLE NUMBER(1) DEFAULT 1,
NET_ID NUMBER(15),
CONTRACT_ADDRESS VARCHAR2(100), 
FROM_ADDRESS VARCHAR2(100), 
TX_HASH VARCHAR2(100),
TREE_ROOT VARCHAR2(100),
BLOCK_NUMBER NUMBER(15),
PENDING NUMBER(1) DEFAULT 0,
CONSTRAINT STAMP_REQUEST_HASH_PK PRIMARY KEY (OBJECT_HASH),
CONSTRAINT STAMP_REQUEST_HASH_PENDING CHECK ((PENDING IS NULL AND TX_HASH IS NOT NULL) OR (PENDING = 0 AND TX_HASH IS NULL)),
CONSTRAINT STAMP_REQUEST_FORCE_SINGLE CHECK (FORCE_SINGLE IN (0,1))
);

CREATE INDEX STAMP_REQUEST_IX1 ON BFAC.STAMP_REQUEST(PENDING);

CREATE INDEX STAMP_REQUEST_IX2 ON BFAC.STAMP_REQUEST(TREE_ROOT);

GRANT SELECT, UPDATE, INSERT on BFAC.STAMP_REQUEST to BFAC_APP;
